### ISSUE TITLE
Suggestions to save a bit of money :)

### ISSUE THREAD

**Issue by kokarn** [adamdevigili/tarkovammo3d#2]
Full disclosure: I'm one of the devs behind tarkov-tools.

Hey! Been seeing this nice repo for a while. Very cool idea with a 3d-graph! Have been thinking about how to incorporate more parameters into ammo charts (especially now with stuff like weapon damage being a thing...)

Do you know that all ammo data is available https://github.com/TarkovTracker/tarkovdata/ in the ammunition.json file and that the tarkov-tools API provides flea market prices as well?

Reading through your code I _think_ this should cover all your needs and be free + open source.

Example query for one way to get flea prices
```
{
  itemsByType(type: ammo) {
    id
    name
    shortName
    iconLink
    lastLowPrice
  }
}
```

**Comment by adamdevigili** [comment]
Hey!

I actually just noticed that over the last few days (actually still have the grpahql playground tab up as I type this) as I picked the project back up. I'll also definitely be switching to grabbing the static ammo file, [actually made a GH project card for it 2 days ago](https://github.com/adamdevigili/tarkov-charts/projects/1#card-65561940). I have local changes to add graphs for attachments (ergo vs recoil vs price), and a couple other ideas as well such as adding different preset transforms to the graph, but I'm still brand new to the plotly library (as well as React as you could probably tell, sort of have no idea what I'm doing 😄) 

A question about the tarkov-tools API, when trying to just get say pistol grips, I can use the `itemsByType(type: mods)` query, but obviously that comes with a lot more than I need. In my development branch, using the BSG API, I'm able to check the `_parent` field to filter down to just pistol grips (`_parent == 55818a684bdc2ddd698b456d`). Is there a similar field I can check/behavior I can implement? 

Thanks for the advice and suggestions! 

Also, tarkov-tools was easily one of my most used sites as I started to get into the game, and it's gotten so much better over time. Thanks for your hard work.

**Comment by kokarn** [comment]
Found the GH project after posting the issue actually, but figured I'd let the issue stay anyway :)

So far we don't have any plans to display that kind of raw data. 

There are a few properties that we will add such as ergo, recoil, etc and we will probably add more categories but the "static" BSG `_parents` would probably be out of scope as that data doesn't make sense unless you understand the structure.

There's also the issue that not all pistol grips are created equal as you can't have any pistol grip on any gun, hence a chart of it would be pretty misleading :)

PS: Your code looks fine! Feel free to post any improvements to the [tarkov-tools repo](https://github.com/kokarn/tarkov-tools/) if you find something missing. We usually accept all PRs :)

**Comment by adamdevigili** [comment]
Added in commit [e523cf](https://github.com/adamdevigili/tarkov-charts/commit/e523cfab7c5b9df0fa6a20bc1f91684786efe04c) 😄.

**Comment by kokarn** [comment]
I have been following, nice work! :)
